### PR TITLE
[WIP] TurboReg2 revival

### PR DESCRIPTION
**Pull request by hadim**
Hi @LeeKamentsky and @ctrueden.
- [x] The code now compiles but some more work is needed.
- [x] I also moved the `groupId` to `fiji.plugin` as I think it could be incorporated in the official plugins at some point.
- [ ] Make it work under IJ1 interface.

For now when the plugin is executed under the IJ1 interface the following error appears `A ImageDisplay is required but none exist.`. Seems to be a limitation of the IJ1 <-> IJ2 layer. I don't know if it can be easily fixed or if we need to use something else than `ImageDisplay`.
- [ ] Transformation are not applied.

When running the plugin, registration seems to be computed but no transformations are applied on the image.

Test dataset is available here : [test.zip](https://github.com/LeeKamentsky/TurboReg2/files/224693/test.zip)

### CODE REVIEW

**Comment by hadim** [comment]
After some investigations, it seems that `TurboRegApply` correctly call `doBatchFinalTransform` for each frames of the stack but I see no differences before and after the transformation.

I don't know if it is a display issue or the transformation that just do nothing.

The fact that the table contains only 3 rows make me think that maybe transformations applied do nothing.

**Comment by ctrueden** [comment]
@LeeKamentsky Do you want to hand this over to the imagej org, or maybe to hadim?

Also, I have some concerns about the licensing issues relating to this project. Though this here PR is obviously not the place to discuss them, I just mention it as a caution before anyone dives into this direction too far.

**Comment by LeeKamentsky** [comment]
Whatever I need to do to hand it over - whoever want to be the champion or
maintainer is fine with me. I did have Philippe's blessing to undertake
this and perhaps he or Michael Unser's group could help with the licensing
issues.

**Comment by ctrueden** [comment]
@hadim What do you think? Do you want to adopt this? If not, I propose we move it to the fiji org.

**Comment by hadim** [comment]
Not really. I don't use it very often... Probably better to move it to fiji org.

**Comment by ctrueden** [comment]
OK @LeeKamentsky, you can transfer it to the `fiji` org any time, and I'll accept it, if that's what you want.

**Comment by ctrueden** [comment]
Merged this, just for completeness... and now I archive the repository! 😜

**Pull request merged**
